{"sid": "91c706acfa8b4afdb7c205bb8b0d492a", "uid": null, "qid": "dc3d078f19d64219bb33623ec8ac246d", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [dc3d078f19d64219bb33623ec8ac246d]\nTraceback (most recent call last):\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.cache/pypoetry/virtualenvs/ai-test-e0q8ujZD-py3.12/lib/python3.12/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/workspaces/Openfabic/app/main.py\", line 85, in execute\n    image_response = stub.call(\n                     ^^^^^^^^^^\n  File \"/workspaces/Openfabic/app/core/stub.py\", line 85, in call\n    raise Exception(f\"Connection not found for app ID: {app_id}\")\nException: Connection not found for app ID: f0997a01-d6d3-a5fe-53d8-561300318557\n", "created_at": "2025-06-08T11:14:44.433318"}], "status": "FAILED", "created_at": "2025-06-08T11:14:11.278306", "updated_at": "2025-06-08T11:14:44.433369", "finished": true}